auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: Lucyliu21.com
url: http://lucyliu21.github.io
feed: /atom.xml
author_info: <a href="http://lucyliu21.github.io/">lucyliu21</a>
